name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to AWS
        run: |
          ssh ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            set -e

            # Update system and install dependencies
            sudo apt update -y
            sudo apt install -y docker.io

            # Ensure Docker service is running
            sudo systemctl start docker
            sudo systemctl enable docker

            # Pull the latest code
            if [ ! -d "app" ]; then
              git clone https://github.com/jasonsanjay21/DevOpsPF.git app
            else
              cd app && git pull origin main
            fi
            
            cd app

            # Build and run Docker container
            docker stop myapp || true
            docker rm myapp || true
            docker build -t myapp .
            docker run -d --name myapp -p 80:80 myapp
          EOF
